version: '3'
# Removing named volumes for now while adding many packages
# `docker compose exec` can be used to update packages
#volumes:
    #nodemodules:
services:
    web:
        build: .
        command: node_modules/.bin/gulp
        environment:
            NODE_ENV: development
        ports:
            - '3000:3000'
            - '9229:9229' # For debug server (not working)
        volumes:
            - .:/home/app/pavlok
            - /home/app/pavlok/node_modules
